### ISSUE TITLE
Permissions saved incorrectly to Solr after removing permissions using nested attributes.

### ISSUE THREAD

**Issue by ojlyytinen** [projecthydra/hydra-head#267]
In Sufia you encounter this by following these steps. First create a private file and share it with another user. As expected, the other user can now access the file. Then remove the sharing, the other user should no longer be able to access the file. But unexpectedly they indeed still can access it. And the permissions edit form will not list them in the shared with list so the owner would have no idea that the other user still has access.

The issue seems to be with handling nested attributes (the permissions) and how to_solr works with those when some attributes are deleted. When Solr is updated all nested permission objects still exist but some may be marked for destruction. to_solr still includes the permission objects in the Solr document despite them being about to be destroyed. Thus wrong information goes to 'edit_access_person_ssim' field in Solr and the file remains accessible.

This same problem can easily happen with any other nested attributes too. In our case we had authors implemented as nested attributes and removing an author still left it in Solr until we fixed it by making sure it's not marked for destruction in to_solr. I'm not sure if handling this generic case should be handled internally in Hydra or not but it's certainly an easy mistake to make when implementing nested attributes. 

Below is an example of how to reproduce this on rails console without Sufia. In Sufia you'd just use the built-in GenericFile instead. To be able to check the behaviour in a browser, you'll of course need the relevant controllers too, or just use Sufia.

```ruby
class GenericFile < ActiveFedora::Base
  include Hydra::AccessControls::Permissions
  include Hydra::AccessControls::Visibility
  include Hydra::WithDepositor
  property :title, predicate: ::RDF::DC.title
end

u1=User.create(email:'test1@example.com', password: 'testtest')
u2=User.create(email:'test2@example.com', password: 'testtest')

f=GenericFile.new
f.title << 'test file'
f.apply_depositor_metadata u1
f.save

# as expected User 2 can't at this point access the file if you try in a browser

f.edit_users += [ u2.user_key ]
f.save

# user 2 can now see and edit the file, as expected

# then change the permissions using nested attributes in the generic file,
# as would happen if you used the edit form for the file in a browser

p=(f.permissions.to_a.select do |x| x.agent_name == u2.user_key end).first
attributes={ permissions_attributes: [ { id: p.id, _destroy: 'true' } ] }

f.attributes=attributes

# permissions still has entries for both users
f.permissions.to_a.length # 2

# but one of them is marked for destruction
p.marked_for_destruction? # true

# This should only include user 1, but it includes both users
f.to_solr['edit_access_person_ssim'] # ["test1@example.com", "test2@example.com"]

f.save

# permissions now only contains the single entry for user 1
f.permissions.to_a.length # 1

# But in browser the other user can still access the document because Solr has
# both users in edit_access_person_ssim

class Search
 include Blacklight::SearchHelper
 include Blacklight::Configurable
end

s=Search.new
s.search_results({q: "id:#{f.id}"}, [:default_solr_parameters, :add_query_to_solr])[0]['response']['docs'][0]['edit_access_person_ssim']
# ["test1@example.com", "test2@example.com"]

# if you update the index again then correct data is pushed to Solr
f.to_solr['edit_access_person_ssim'] # ["test1@example.com"]
f.update_index

s.search_results({q: "id:#{f.id}"}, [:default_solr_parameters, :add_query_to_solr])[0]['response']['docs'][0]['edit_access_person_ssim']
# ["test1@example.com"]

# and if you now try in a browser, user 2 can't access the document
```

**Comment by jcoyne** [comment]
Hi Olli. Thanks for the problem report.  Can you tell me which version of
ActiveFedora are you using when you encounter this problem?

-Justin

**Comment by jcoyne** [comment]
I think I see the trouble.  The solr document for the `GenericFile` gets written before the autosave association callback is run. So calling `.to_solr` on the `GenericFile` gives the correct result, but that wasn't actually the result that was written to solr.

```ruby
f.save
=> true
f.to_solr["edit_access_person_ssim"]
=> ["test1@example.com"] # this looks correct

# what was actually written to solr:
ActiveFedora::SolrService.query("id:#{f.id}").first['edit_access_person_ssim']
=> ["test1@example.com", "test2@example.com"] # but this is wrong
```

**Comment by ojlyytinen** [comment]
I tried this on a clean new Sufia install which had ActiveFedora 9.1.2. I also tried on a slightly dated plain Hydra install which had ActiveFedora 9.1.1.

And yes, that's exactly the problem. edit_access_person_ssim is wrong in Solr. The indexing seems to happen before the permission objects which are marked_for_destruction? are completely removed.

Not sure if this is better fixed in ActiveFedora or Hydra. Certainly if it was fixed in ActiveFedora and those marked_for_destruction? objects never made their way to the to_solr function then it'd be almost impossible for people to do the same mistake with other nested attribute fields. But I imagine that maybe those marked_for_destruction? objects are needed in some after filters.

**Comment by jcoyne** [comment]
I attempted to change the order of where the indexing happens, but that breaks a spec (https://github.com/projecthydra/active_fedora/blob/master/spec/integration/has_many_associations_spec.rb#L76-L105) so I don't think we can go down that route. I think we can filter out the `marked_for_destruction?` records from the indexer, to fix this problem generally, however, that wouldn't help this case, as it's a custom `to_solr` function: https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/models/concerns/hydra/access_controls/permissions.rb#L14-L23
