### ISSUE TITLE
hydra-access-controls - is it deprecated?

### ISSUE THREAD

**Issue by reggieb** [projecthydra/hydra-head#280]
hydra-access-controls appears to be deprecated as shown here:

https://github.com/projecthydra-deprecated/hydra-access-controls

The README for that pages states that the functionality is provided as part of this gem (hydra-head).

But the hydra-access-controls gem is still specified in hydra-head.gemspec

Am I missing something, or doesn't that mean the same hydra-access-controls classes and methods are being defined in two places within hydra-head? 

If hydra-access-controls has been relocated within hydra-hear, I think the line:

    s.add_dependency('hydra-access-controls',   version)

needs to be removed from hydra-head.gemspec

**Comment by jcoyne** [comment]
hydra-access-controls as a stand alone repository is deprecated. but the gem itself is not deprecated.  It's moved into hydra-head.  Hydra-head is a meta-gem that has no code itself, but depends on hydra-access-controls and hydra-core.

**Comment by reggieb** [comment]
OK - I see it now. 

The files included within the hydra-head gem are defined by this in hydra-head.gemspec

   s.files = ['lib/hydra/head.rb']

So the gem only contains one file.

Thanks @jcoyne - I must have been too focused on dependencies to look at the gemspec more closely.

BTW, this method in lib/hydra/head.rb is redundant i think:

    def self.version
      HydraHead::VERSION
    end

As HydraHead::VERSION isn't defined anywhere.

**Comment by jcoyne** [comment]
HydraHead::VERSION is defined here: 

https://github.com/projecthydra/hydra-head/blob/3f1e3b925f0f8c11b2c2f942a8f83cc96b605225/hydra-core/lib/hydra-head/version.rb#L2

but that does seem like the wrong place for it to be.

**Comment by reggieb** [comment]
My point is, as that file isn't including in the gemspec, it isn't distributed with the gem and therefore the method is broken when the code is loaded as a gem.

**Comment by jcoyne** [comment]
@reggieb You're right. Do you want to open an issue for that?

```ruby
 HydraHead.version
NameError: uninitialized constant HydraHead::VERSION
```

**Comment by reggieb** [comment]
It more complicated than that. The version number used in hydra-core.gemspec, hydra-access-controls.gemspec and hydra-head.gemspec is defined in /HYDRA_VERSION

So version is defined in two places: 

- hydra-code/lib/hydra-head/version.rb
- HYDRA_VERSION

I've forked the repo. Do you mind if i have a go at tidying this up?
