### ISSUE TITLE
Do not generate repeat entries in mime_types.rb

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/hydra-head#286]
We may want to make the [MIME type-related method in this generator](https://github.com/projecthydra/hydra-head/blob/6c3fdff0bd82eaae4a36468880eea247cb0bf892/hydra-core/lib/generators/hydra/head_generator.rb#L79-L86) deal with `mime_types.rb` in a more nuanced way. For instance, before injecting each line, we should check to see if it already exists.

At least one person found multiple MIME type blocks in that file, which you can read more about here: https://groups.google.com/d/msg/hydra-tech/Bcp64Z6en_Y/d2gJ7lWGAwAJ

**Comment by mjgiarlo** [comment]
@jcoyne The message on hydra-tech said they wound up with this in `mime_types.rb`:

```ruby
Mime::Type.register "application/n-triples", :nt
Mime::Type.register "application/json", :jsonld
Mime::Type.register "text/turtle", :ttl
Mime::Type.register 'application/x-endnote-refer', :endnote

Mime::Type.register "application/n-triples", :nt
Mime::Type.register "application/ld+json", :jsonld
Mime::Type.register "text/turtle", :ttl
Mime::Type.register 'application/x-endnote-refer', :endnote
```

Maybe they just ran a generator twice and this isn't something we can fix in hydra-head?

**Comment by jcoyne** [comment]
Since the generator was changed, it couldn't detect that it shouldn't perform the operation a second time. If we hadn't changed the generator then it wouldn't have run twice.

**Comment by mjgiarlo** [comment]
:ok:
