### ISSUE TITLE
Hydra::AccessControlsEnforcement#add_access_controls_to_solr_params broken (9.1.0+)

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra/hydra-head#294]
In commit 4d6602301966cfc6c69a103b24de309ffaccdf41, one of the params was removed from the method signature of `Hydra::AccessControlsEnforcement#add_access_controls_to_solr_params`.  AFAICT that has never been compatible with Blacklight 5.10+ (the commit message says changes were made for BL 5.10 compatibility).  I have to patch the method like this to get my app to work:

```ruby
  # PATCH bug in Hydra::AccessControlsEnforcement - missing parameter                                                             
  def add_access_controls_to_solr_params(request_params, solr_params)
    apply_gated_discovery(solr_params)
  end
```

@jcoyne

**Comment by awead** [comment]
Are you using the new SearchBuilder logic? The upgrade to BL 5.10 also started using this new class as a means of building together different solr queries.

**Comment by jcoyne** [comment]
Adam is right.  This method is intended to be on a SearchBuilder and not on
the Controller.  Blacklight has evolved to separate the concern of building
a Solr query into the SearchBuilder class.  Since
add_access_controls_to_solr_params is concerned with building a query, is
has been moved there.  All custom methods on SearchBuilder are called with
a single parameter.

-Justin

**Comment by awead** [comment]
@dchandekstark  here's an example of what we did:
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/models/search_builder.rb
We didn't have to change anything, other than adding what was already there.

**Comment by dchandekstark** [comment]
My problem seems to be caused by putting Blacklight and Hydra mixins in my ApplicationController, for which there must have been good reasons at the time, a couple of years ago. :)

**Comment by jcoyne** [comment]
@dchandekstark can this be closed?
