### ISSUE TITLE
Supply an XML schema for Hydra rightsMetadata

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/hydra-head#31]
Formerly HYDRA-842

There exists no documented shared namespace and schema for Hydra rightsMetadata. Attached is a "strawman" example from Eddie Shin. A published schema would be a valuable piece of shared documentation.

**Comment by terrellt** [comment]
XML rights metadata isn't a thing anymore. Close? @jcoyne

**Comment by jcoyne** [comment]
Sure.
