### ISSUE TITLE
[Hydra CI] hydra-core tests not running

### ISSUE THREAD

**Issue by mark-dce** [projecthydra/hydra-head#344]
Through commit e3bab009cd2ef63502f8b43ac1cbd4e0a4b7c9d9, the [Hydra CI] hydra-access-controls test suite ran 302 examples and the **[Hydra CI] hydra-core** test suite **ran 46 examples** - see Travis logs  here https://travis-ci.org/projecthydra/hydra-head/jobs/124316006

After commit 0e24d21c8321a31dcb8ef9ace8e623258ac44412, the [Hydra CI] hydra-access-controls test suite still runs 302 examples but the **[Hydra CI] hydra-core** **no longer runs any examples** - see Travis logs here https://travis-ci.org/projecthydra/hydra-head/jobs/128083163

**Comment by jcoyne** [comment]
It's complaining about:
```
[error]: Missing 'redcloth' gem for Textile formatting. Install it with `gem install redcloth`
```
