### ISSUE TITLE
Template installer should run `rails generate rspec:install`

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/hydra-head#409]
<a href="https://github.com/bess"><img src="https://avatars0.githubusercontent.com/u/65608?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bess](https://github.com/bess)**
_Tuesday Apr 04, 2017 at 22:17 GMT_
_Originally opened as https://github.com/projecthydra-labs/hyrax/issues/708_

----

### Descriptive summary

Re: hydra-head `master` and likely many of its releases.

### Rationale

When installing e.g. Hyrax via the template installer, after you generate a new work type, rspec tests are generated but they won't run because rails_helper.rb doesn't exist.

### Expected behavior

The template should run `rails generate rspec:install` to create all the files necessary to run rspec

### Actual behavior

```
paz:laevigata bess$ bundle exec rake spec
/Users/bess/.rvm/rubies/ruby-2.3.3/bin/ruby -I/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/rspec-core-3.5.4/lib:/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/rspec-support-3.5.0/lib /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
/usr/local/projects/hyrax/laevigata/spec/actors/hyrax/actors/etd_actor_spec.rb:3:in `require': cannot load such file -- rails_helper (LoadError)
```

### Steps to reproduce the behavior

1. Install a new app via the template installer
1. Create a new work type
1. Attempt to run test suite via `rake spec` or `rspec spec`

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> I believe this should be moved to the hydra-head repository as it is the generator that installs rspec-rails: https://github.com/projecthydra/hydra-head/blob/master/hydra-core/lib/generators/hydra/head_generator.rb#L28

**Comment by mcritchlow** [comment]
I can take a pass at adding this to the generator, seems fairly straightforward. Is there a recommended place to test such a change?

**Comment by no-reply** [comment]
@mcritchlow I think the generators are generally un- or under-tested throughout the stack. I'd be :+1: on a fix that's untested for that reason, but I'm also in favor of starting to fix that. We might adopt d omething like https://github.com/stevehodgkiss/generator_spec ?

If we could land on a pattern, I'd be interested in adding tests to the hyrax model generators, too.

**Comment by mcritchlow** [comment]
@no-reply yeah, that reference is kinda what i was imagining 👍 So for now, I guess I'll add the command to the template and maybe we could mint another issue for discussing a testing pattern for templates/generators?

**Comment by no-reply** [comment]
Sounds good.
